### ISSUE TITLE
How to implement product info/relationship?

### ISSUE THREAD

**Issue by vitek-dev** [simara-svatopluk/cart#14]
You know, classic use case - you want to display cart contents like "product name - quantity - total price".

We have product_id, but as you said, relationships outside the aggregate are forbidden. So how can I fetch all necessary info for displaying cart? 

Is it OK if I do it similar to Prices? Pseudo-code:
```php
class Item {

  public function toDetail(Prices $prices, ProductInfo $productInfo): ItemDetail
  {
    return new ItemDetail(
      price: $prices->getPriceForProduct($this->product_id),
      product_title: $productInfo->getBasicInfoForProduct($this->product_id)->getTitle(),
    );
  }

}
```

Or should it be realized on presentation layer (array_map to get all products ids and then second request to product repository/productusecase to provide the products)?

By the way, isn't this single-responsibility violation? CartDetail and ItemDetail are basically DTOs - shouldn't exist some third class transforming Entity into DTO?

Thanks!!

**Comment by simara-svatopluk** [comment]
I would definitely prefer combining these information on the presentation layer. Eg.

```php
class CartItemInUI {
    public function __construct(
        public readonly string $productId,
        public readonly Price $price,
        public readonly int $amount,
        public readonly string $title,
    ) {
    }
}
```

with the `array_map` as You describe.

> By the way, isn't this single-responsibility violation? CartDetail and ItemDetail are basically DTOs - shouldn't exist some third class transforming Entity into DTO?

It could and don't have to be.

My thinking process behind this Cart aggregate is that it encapsulates writing logic together with reading possibilities - one unit. Therefor it doesn't expose internals - can be refactored, and provides reading methods - can be observed/tested.

I think it's a valid approach.

### Off-topic
Recently I encountered event sourcing, and I became a huge fanboy of it.... So today I would recommend....
* store event
* project as many aggregates as You need - they encapsulate only writing logic
* project as many reading projections as You need.

**Comment by vitek-dev** [comment]
Thanks for your response! :) Could you please be little more specific with the real-world implementation? Where/How to fill the DTO with data?

Some real world situation. Let's take your domain as an example and let's imagine there is another Products aggregate. Also let's imagine there is Nette aplication around the domain, because we need some UI.

### Project structure 

I would start probably with project structure - is the following structure OK?

```
| - app
  | - Presenters
    | - templates
      | - Cart
        | - default.latte
  | - CartPresenter.php
| - src
  | - Simara
    | - Cart
      | - Application
      | - Domain
      | - Infrastructure
| - vendor
```

Nette Presenters are working with UseCases in Application layer to interact with domain. E.g. CartPresenter would probably call CartUseCase->detail to get more information about current cart. Or CartUseCase->add to add some products, etc.

What is the right place to put the CartItemInUI class itself and the logic around that? I guess it's not presenter because testing presenters is pain. Should it be some service at presentation layer? Like some folder "Services" next the "Presenters"?

### CartItemInUI 

What is the right way to put data into the Dto, when half of data comes from Cart aggregate and half from Products aggregate? 

According to your videos and articles (they are excellent!) I realized I am used to writing the anemic model and not rich model (injecting services into entity is really new for me), so this is probably the way how I would solve the problem:


```php
namespace App\Services;

class CartProductsService 
{
  public funciton __construct(
    private CartUseCase $cartUseCase,
    private ProductUseCase $productUseCase,
  ) { }

  public function getCart(): array
  {
    $result = [];

    $items = $this->cartUseCase->detail()->getItems();
    $productsIds = array_map(fn (ItemDetail $itemDetail) => $itemDetail->getProductId(), $items);

    foreach ($items as $item) {
      $product = $this->productUseCase->get($item->getProductId());
      
      $result[] = new CartItemInUI(
        productId: $item->getProductId(),
        price: $item->getPrice(),
        amount: $item->getAmount(),
        title: $product->getTitle(),
      );
    }

    return $result;    
  }
}
```

But in this solution I can see a problem with calling `productUseCase` in each iteration of foreach - each iteration means separate query into database at the infrastructure level. 
From one point of view I am depending on abstraction so I don't care how the repository find the result. But from another point of view I really do care because I will feel the number of queries on bad performance. 

I think I can't access Repository from presentation layer because it's too deep. So am I going well if I create some getProductsByParams on Application layer, and one of the params could be the array of products ids I want?

**Comment by simara-svatopluk** [comment]
Hi... long answer short: It's going to be long :-P

> I think I can't access Repository from presentation layer because it's too deep.

Do whatever works. Please don't follow strict rules just to fulfill them. If You need some data, use a repository, why not... optimize later :-)

I usually think backwards. Not "what do I have and how to do something?", but "what is the goal, what do I need?"

So in this case my goal is to
# display cart contents like "product name - quantity - total price

And I'll stick to this. And will do as little of code as possible.

### Template

There surely must be a template (and in the Nette probably also a presenter). Cool

```
| - app
  | - Presenters
    | - templates
      | - Cart
        | - default.latte
    | - CartPresenter.php
```

Ok, now I need to display data in structure

### Data Structure

This data structure will be the CartItemInUI from https://github.com/simara-svatopluk/cart/issues/14#issuecomment-1113102138

```php
class CartItemInUI {...}
```

```
| - app
  | - Presenters
    | - templates
      | - Cart
        | - default.latte
    | - CartPresenter.php
    | - CartItemInUI.php <--- here because the purpose is to display data in template
```

Ok, now let's fill it by data

### Filling data structure by static data

In the first step I would put some static data to presenter just to see it works..

```php
public function renderDefault() {
    $this->template->cartItems = [new CartItemInUI("productId15", Price("18.20"), 1, "foo product")]
}
```

Ok, now it "works", and I can forget about the data structure, and where to place it.

Aaaand... now I have to think for the first time. Next step... What is the next step?
Hm.. I need to get these cartItems from somethere. I don't really care where from, and I don't know it now. Ideally it would be "assembled" in that place in the form of list `array<int, CartItemInUI>`.

And I'll do two steps in one - I'll also have to specify which cart do I want - provide `cart id` that will be stored let's say in session.

### Load data from somewhere

Presenter:
```php
class CartPresenter {
    public function __construct(
        private Session $session,  // Nette stuff
        private CartItemInUIProvider $providerOfCartInUi,
    ) {
    }

    public function renderDefault() {
        $cartId = $this->session->section('cart')->get('id'); //hopefully something useful is there!
        assert(is_string($cartId));
        $this->template->cartItems = $this->providerOfCartInUi->getByCartId($cartId);
    }
}
```

Now we defined interface before thinking how to do it!

```php
interface CartItemInUIProvider {
    /** @return array<int, CartItemInUI> */
    public function getByCartId(string $cartId): array;
}
```

And where to place it?!

UI layer, application, domain?

I would vote for the UI because it does exactly what the UI needs

```
| - app
  | - Presenters
    | - templates
      | - Cart
        | - default.latte
    | - CartPresenter.php
    | - CartItemInUI.php
    | - CartItemInUIProvider.php
```

### Load data from a concrete place

Now we have an interface, but where is the code?!

Now I'll state that responsibility of the "concrete place" is our application. It's our code, and we're responsible 
for providing correct data.

```
| - app
  | - Presenters
    | - templates
      | - Cart
        | - default.latte
    | - CartPresenter.php
    | - CartItemInUI.php
    | - CartItemInUIProvider.php
  | - Application
    | - ApplicationProvidingCartItemsToUI.php
```

```php
class ApplicationProvidingCartItemsToUI implements CartItemInUIProvider {
    /** @return array<int, CartItemInUI> */
    public function getByCartId(string $cartId): array {
        return [new CartItemInUI("productId15", Price("18.20"), 1, "foo product")]
    }
}
```

This will be the place where the fetching+combining logic will be.

And now let's shuffle classes a bit to achieve inverse dependency between our application and usage - the Presenter.

### Shuffle classes (optional)

```
| - app
  | - Presenters
    | - templates
      | - Cart
        | - default.latte
    | - CartPresenter.php
  | - Application
    | - InputInterface
      | - CartItemInUI.php
      | - CartItemInUIProvider.php
    | - ApplicationProvidingCartItemsToUI.php
```

Application is a self-sufficient unit - without dependencies. And Presenter only uses it.

And now I can really focus on Your question - how to fetch&combine data!

### How to fetch data

We'll need the `CartRepository` to load the real content of the cart.
Product name later...

```php
class ApplicationProvidingCartItemsToUI implements CartItemInUIProvider {
    public function __construct(
        private CartRepository $cartRepository,
        private Prices $prices,
    ) {
    }

    /** @return array<int, CartItemInUI> */
    public function getByCartId(string $cartId): array {
        $cart = $this->cartRepository->get($cartId);
        $detail = $cart->calculate($prices);
        
        return array_map(function(ItemDetail $itemDetail) {
            return new CartItemInUI($itemDetail->getProductId(), $itemDetail->getPrice(), $itemDetail->getAmount(), 
            "foo product");
        }, $details->getItems());
    }
}
```

Quite straight-forward. I don't want more interfaces.

Just to repeat - this is our application (application layer), and it's responsibility is to fulfil the use-case. 

And finally the hard part - fetch product names, and combine data!

### How to fetch&combine data

Product names are store somewhere, and we don't care where. And Your requirement is to have it efficient, and I buy 
it!

Let's rearrange the code to production-ready style - we'll use an array `$productNames` that will hold names of all 
products in carts, and we'll use this array in the main `array_map` transformation.

```php
    /** @return array<int, CartItemInUI> */
    public function getByCartId(string $cartId): array {
        $cart = $this->cartRepository->get($cartId);
        $detail = $cart->calculate($prices);
        
        $productIds = array_map(function(ItemDetail $itemDetail) {
            return $itemDetail->getProductId();
        }, $details->getItems());
        $productNames = array_map(function(string $productId) {return "foo product";});
        
        return array_map(function(ItemDetail $itemDetail) {
            return new CartItemInUI($itemDetail->getProductId(), $itemDetail->getPrice(), $itemDetail->getAmount(), 
            $productNames[$itemDetail->getProductId()]);
        }, $details->getItems());
    }
```

A bit more complicated, but my goal is achieved - the second `array_map` is production-ready as there is nothing 
hardcoded. It's also efficient! And prepared to be efficient.

And now we have to finally kick out the hardcoded `foo product title`.

We'll do it by an interface - we need product titles, but we don't care where are they stored

```php
    /** @return array<int, CartItemInUI> */
    public function getByCartId(string $cartId): array {
        ...
        $productIds = array_map(function(ItemDetail $itemDetail) {
            return $itemDetail->getProductId();
        }, $details->getItems());
        $productNames = $this->productTitles->findByProductIds($productIds);
        ...
    }
```

Final form of ApplicationProvidingCartItemsToUI

```php
class ApplicationProvidingCartItemsToUI implements CartItemInUIProvider {
    public function __construct(
        private CartRepository $cartRepository,
        private Prices $prices,
        private ProductTitles $productTitles,
    ) {
    }

    /** @return array<int, CartItemInUI> */
    public function getByCartId(string $cartId): array {
        $cart = $this->cartRepository->get($cartId);
        $detail = $cart->calculate($prices);
        
        $productIds = array_map(function(ItemDetail $itemDetail) {
            return $itemDetail->getProductId();
        }, $details->getItems());
        $productNames = $this->productTitles->findByProductIds($productIds);
        
        return array_map(function(ItemDetail $itemDetail) {
            return new CartItemInUI($itemDetail->getProductId(), $itemDetail->getPrice(), $itemDetail->getAmount(), 
            $productNames[$itemDetail->getProductId()]);
        }, $details->getItems());
    }
}
```

And again, we defined an interface before thinking "how" to implement it.

```php
interface ProductTitles {

    /**
     * @var array<int> $ids
     * @return array<string>
     */
    public function findByProductIds(array $ids): array;
}
```

```
| - app
  | - Presenters
    | - templates
      | - Cart
        | - default.latte
    | - CartPresenter.php
  | - Application
    | - InputInterface
      | - CartItemInUI.php
      | - CartItemInUIProvider.php
    | - OutputInterface
      | - ProductTitles <--- here
    | - ApplicationProvidingCartItemsToUI.php
```

I decided to put it into `OutputInterface` namespace to emphasize that our Application layer needs it but don't care 
how is it done.

And now just fetch data from DB

### Just fetch data from DB

I'll use a Dibi because it has an easy interface. Use whatever suits to You.

```php
class ProductTitlesByDibi implements ProductTitles {

    public function __construct(private Connection $connection);

    /**
     * @var array<int> $ids
     * @return array<string>
     */
    public function findByProductIds(array $ids): array {
        // hope this works... just guessing
        return $this->connection->fetchPairs('SELECT id, title FROM product WHERE id in (?)', $ids);
    }
}
```

### Final project structure

```
| - app
  | - Presenters
    | - templates
      | - Cart
        | - default.latte
    | - CartPresenter.php
  | - Application
    | - InputInterface
      | - CartItemInUI.php
      | - CartItemInUIProvider.php
    | - OutputInterface
      | - ProductTitles
    | - ApplicationProvidingCartItemsToUI.php
  | - Infrastructure
    | - Dibi <-- I like to organize by technology
      | - ProductTitlesByDibi.php
```


I'm sure there is a tones of typos, and I'm sure the amount of ideas is huge.. and really concentrated.

But I used this step-by step approach as I believe You can get better each idea, and I wanted also to present how do 
I think.

And by the way I really develop code in this style...

Hope my long, long, long answer will help You!

**Comment by simara-svatopluk** [comment]
@davtk is it helpful :top: ?

**Comment by vitek-dev** [comment]
Yes it is much helpful! Sorry for late reply, i tried to implement that because it's way to understand that better :)

**Comment by simara-svatopluk** [comment]
@davtk great, so You have practical experience!

What is Your impression after trying it? Does it make sense? Is it complicated? Did it take a long time to implement?

Any feedback would be great for me :-) Eg. if I later decide to rephrase this reply to an article :-P

**Comment by vitek-dev** [comment]
In this example it is not really complicated, I would say I have similar process in my head like you. For me there are probably just three points, which are also related to whole DDD course:

- Still need to kick Anemic model out of my head, and also Doctrine two-way-relations-everywhere way of thinking :D
- This example looks nice and clean, but implementation in more complex system is bigger challange (probably more impressions come after implementing that somewhere)

What I'm really wondering is - how many interfaces should be in the application. I'm talking about the Product titles for example. 
Normally I would take some ProductRepository, fetch Products and get Titles from the Product entity. But in this example you are using extra interface (yes, there is no product repository :) ) only for titles.

**Comment by simara-svatopluk** [comment]
Thanks for sharing Your point of view.

The amount of interfaces grows rapidly in the early stages of project. And it might be scary, and also complex, difficult to navigate.

But once the project switches into production, and maintenance - maintenance not always by the author of code - it's really calming feeling knowing one DTO/interface is used in one or two places. I have always really safe feelings - I know I cannot destroy the whole system by doing my change - it's impossible, because I understand two places where the DTO/interface is used.

Chaning something I don't understand that is used in dozens of places - like ProductRepository - is scary, and therefore I take extra effort to not break anything... And still I usually do so.
