### ISSUE TITLE
Handle price with floats is not a good idea

### ISSUE THREAD

**Issue by damianopetrungaro** [simara-svatopluk/cart#2]
Here a quick explanation, please consider using integers
https://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency

**Comment by simara-svatopluk** [comment]
You are right, I had even part of talk about this topic recently :-D

Thanks for noticing, will fix soon

**Comment by simara-svatopluk** [comment]
Kept the `Price` value object because it is the domain concept, but changed the interface to work with `strings`. Strings suite well for use cases - we can still work with decimals like `10.50`, integers would force us to use prices in cents like `1050`.

But we don't have to reinvent the wheel, so we use internally `Money`.

Thanks for the issue, it lead to improvement :+1:
